### ISSUE TITLE
Support dart entrypoint

### ISSUE THREAD

**Issue by xiaowei-guan** [flutter-tizen/engine#111]
Typically, a Flutter app begins execution at the Dart method called main(), however this is not required. Developers can specify a different Dart entrypoint

**Comment by swift-kim** [comment]
The plugin build system (https://github.com/flutter-tizen/flutter-tizen/blob/20007aa24f83ff21ff3f5314410f16e448b0d75c/lib/tizen_plugins.dart#L194) should be a current blocker for this. I'll check if there's any way to work around if you give me some example of how to test this. (You're not referring to named routes, right?)

**Comment by swift-kim** [comment]
For those who are interested:

Custom entry points can be specified in Dart code using `@pragma("vm:entry-point")`: https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md

The Android embedder supports starting an engine from a custom entry point:

```java
if (dartEntrypoint == null) {
  dartEntrypoint = DartEntrypoint.createDefault(); // main()
}

if (activeEngines.size() == 0) {
  engine = createEngine(context);
  engine.getDartExecutor().executeDartEntrypoint(dartEntrypoint);
} else {
  engine = activeEngines.get(0).spawn(context, dartEntrypoint);
}
```

What you are trying to do is to set different entry points for spawned engine instances, right?

If so, there's another approach to achieve a similar goal without creating multiple entry points by using [Navigator](https://flutter.dev/docs/cookbook/navigation/named-routes). However, it will result in additional complexity as described [here](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#initial-route-with-a-cached-engine):

> Developers who would like to use the same FlutterEngine between different Activitys and Fragments and switch the route between those displays need to setup a method channel and explicitly instruct their Dart code to change Navigator routes.

**Comment by bwikbs** [comment]
@xiaowei-guan 
Is the purpose of this preparation for the  FlutterEngineGroup API? If so, thanks! :smile:

**Comment by xiaowei-guan** [comment]
> For those who are interested:
> 
> Custom entry points can be specified in Dart code using `@pragma("vm:entry-point")`: https://github.com/dart-lang/sdk/blob/master/runtime/docs/compiler/aot/entry_point_pragma.md
> 
> The Android embedder supports starting an engine from a custom entry point:
> 
> ```java
> if (dartEntrypoint == null) {
>   dartEntrypoint = DartEntrypoint.createDefault(); // main()
> }
> 
> if (activeEngines.size() == 0) {
>   engine = createEngine(context);
>   engine.getDartExecutor().executeDartEntrypoint(dartEntrypoint);
> } else {
>   engine = activeEngines.get(0).spawn(context, dartEntrypoint);
> }
> ```
> 
> What you are trying to do is to set different entry points for spawned engine instances, right?
> 
> If so, there's another approach to achieve a similar goal without creating multiple entry points by using [Navigator](https://flutter.dev/docs/cookbook/navigation/named-routes). However, it will result in additional complexity as described [here](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#initial-route-with-a-cached-engine):
> 
> > Developers who would like to use the same FlutterEngine between different Activitys and Fragments and switch the route between those displays need to setup a method channel and explicitly instruct their Dart code to change Navigator routes.

Yes, we try set entry point for flutter engine on Tizen.
``` cpp
FlutterProjectArgs args = {};
args.custom_dart_entrypoint = 
···
I tested it today, if we set custom_dart_entrypoint , we can run this entrypoint successful.

**Comment by xiaowei-guan** [comment]
> @xiaowei-guan
> Is the purpose of this preparation for the FlutterEngineGroup API? If so, thanks! 😄
we 


> @xiaowei-guan
> Is the purpose of this preparation for the FlutterEngineGroup API? If so, thanks! 😄

we add this for multiple screen based on EOM, run two engines, not share memeory.
and I find if we want implement FlutterEngineGroup, Entrypoint is required.

**Comment by swift-kim** [comment]
This feature may be needed by https://github.com/flutter-tizen/flutter-tizen/issues/143.

Maybe we can implement this when https://github.com/flutter-tizen/engine/pull/133 is merged (to avoid conflicts).

**Comment by xiaowei-guan** [comment]
Dart entrypoint for engine(https://github.com/xiaowei-guan/engine/commit/163bb68f6b053f82e072c7eb6eac5d838457ad12)

**Comment by swift-kim** [comment]
Implemented by https://github.com/flutter-tizen/engine/pull/149.

**Comment by swift-kim** [comment]
We need to update the tool side as well in order to be able to use this feature.
