### ISSUE TITLE
Support to get native window

### ISSUE THREAD

**Issue by xiaowei-guan** [flutter-tizen/engine#167]
when I implement presentation displays plugin, engine should provide interface for getting elm window.
I think other plugins may also need this interface in the future.

Issues(Get ecore_wl2_window from elm window)
- [ ] Rotation .
- [ ] Create egl window fail on RPI.
- [x] Black screen when launch app.

**Comment by swift-kim** [comment]
Are you looking for something similar to Windows's `FlutterDesktopPluginRegistrarGetView()` and `FlutterDesktopViewGetHWND()`?

**Comment by bwikbs** [comment]
That seems to be a useful approach. If we use that interface, we need to modify the current platform view interface too.

**Comment by xiaowei-guan** [comment]
> Are you looking for something similar to Windows's `FlutterDesktopPluginRegistrarGetView()` and `FlutterDesktopViewGetHWND()`?

 yes,  some plugins need this interface which require native window.

**Comment by xiaowei-guan** [comment]
# https://github.com/xiaowei-guan/engine/commit/56a200c3ec936a8d79d102cd734043bb2a22e00e
This is initial version, I don't test it. I will test it next week.
I not sure whether has performance issue when we use elm_window to create ecore_window.

**Comment by xiaowei-guan** [comment]
If get ecore window form elm window, enlightment will crash when exit application.

**Comment by xiaowei-guan** [comment]
> The elm window is also required by other plugins. cc @seungsoo47 so based on your work, I tried it too. and I solved the crash.([bbrto21@52742b4](https://github.com/bbrto21/engine/commit/52742b4760e742932c77ad8e76e8f77771ca26f4)) since the wl2 window came from elm_win, so I decided that explicit deletion of wl2 window is not necessary.
> 
> but I faced a new problem. If you use elm_win, a black screen appears first when the app is launched. I haven't made any further progress here.

I have fixed black screen issue, we need override Show method,:
``` C++
void TizenRendererEcoreWl2::Show() {
  ecore_wl2_window_show(GetEcoreWindow());
}
```

**Comment by bbrto21** [comment]
> I have fixed black screen issue, we need override Show method,:

@xiaowei-guan Great!

**Comment by swift-kim** [comment]
I have a question. In which scenario the elm window will be required? Isn't the ecore_wl2 window sufficient for the purpose?

**Comment by xiaowei-guan** [comment]
> I have a question. In which scenario the elm window will be required? Isn't the ecore_wl2 window sufficient for the purpose?

As far as I know:
1.If we want to implement EOM plugin, we need run engine with a elm window(https://docs.tizen.org/development/sample/native/UI/EOM)
2.In the process of developing video plugin with hole, we need set a window to player,  we can set ecore_wl2  window, but we need copy player_internal.h to tizen sdk.
2.tv-viewer plugin.
3.IME plugin.

It would be better if these modules provide interfaces for ecore_wl2 window

**Comment by swift-kim** [comment]
@xiaowei-guan I don't currently know what EOM is, but for other things you just need a pointer to an **ecore_wl2** window but not necessarily an elm window, right? I'd like to avoid adding the elm window initialization step to our embedder as much as possible before we evaluate its performance impacts precisely. I'm currently even trying to remove the call to `elm_init` inside AppFW's `ui_app_main` because elm is not used by Flutter apps (non wearable) and it takes up around 50 ms of the total startup time. As a reference, here's a profiling result of a simple counter app on arm64 rpi4 - [simple_native_app.zip](https://github.com/flutter-tizen/engine/files/7607649/simple_native_app.zip) (recorded by perf during launch, sampling rate=5000).

**Comment by xiaowei-guan** [comment]
> I have a question. In which scenario the elm window will be required? Isn't the ecore_wl2 window sufficient for the purpose?

I also tend to avoid using elm window.  If so, there is no need to add this.

**Comment by bbrto21** [comment]
> 2.In the process of developing video plugin with hole, we need set a window to player, we can set ecore_wl2 window, but we need copy player_internal.h to tizen sdk.

I want to make one thing clear, so I'm asking. 
To support video plugin with hole, do we have to use elm_win or copy the internal header of player to video_plugin source dir(or tizen sdk rootstrap)?

**Comment by xiaowei-guan** [comment]
> > 2.In the process of developing video plugin with hole, we need set a window to player, we can set ecore_wl2 window, but we need copy player_internal.h to tizen sdk.
> 
> @xiaowei-guan I want to make one thing clear, so I'm asking. To support video plugin with hole, do we have to use elm_win or copy the internal header of player to video_plugin source dir(or tizen sdk rootstrap)?

when create video player:
if set elm window, need call player_set_display(this api in player.h)
if set ecore window, need call player_set_ecore_wl_display(this api in player_internal.h)
Tizen SDK not includes player_internal.h.

**Comment by swift-kim** [comment]
In that case, you could use dlopen to use an internal API in your plugin code without having to copy the internal header file.

For instance, the internal API `__dlog_vprint` can be referenced in the following way.

```cpp
#include <dlfcn.h>

#include <cstdarg>

// Variable declaration.
int (*dlog_vprint_)(log_id_t, int, const char*, const char*, va_list);

// Do dlopen and dlsym. This should be done only once.
void* handle = dlopen("libdlog.so.0", RTLD_LAZY);
if (!handle) {
  DLOG_ERROR("Failed to load a library: %s", dlerror());
  return false;
}
*(void**)(&dlog_vprint_) = dlsym(handle, "__dlog_vprint");
if (!dlog_vprint_) {
  DLOG_ERROR("Symbol not found: %s", dlerror());
  dlclose(handle);
  return false;
}

// Call the function.
dlog_vprint_(LOG_ID_MAIN, priority, tag, format, args);
```

**Comment by xiaowei-guan** [comment]
> In that case, you could use dlopen to use an internal API in your plugin code without having to copy the internal header file.
> 
> For instance, the internal API `__dlog_vprint` can be referenced in the following way.
> 
> ```c++
> #include <dlfcn.h>
> 
> #include <cstdarg>
> 
> // Variable declaration.
> int (*dlog_vprint_)(log_id_t, int, const char*, const char*, va_list);
> 
> // Do dlopen and dlsym. This should be done only once.
> void* handle = dlopen("libdlog.so.0", RTLD_LAZY);
> if (!handle) {
>   DLOG_ERROR("Failed to load a library: %s", dlerror());
>   return false;
> }
> *(void**)(&dlog_vprint_) = dlsym(handle, "__dlog_vprint");
> if (!dlog_vprint_) {
>   DLOG_ERROR("Symbol not found: %s", dlerror());
>   dlclose(handle);
>   return false;
> }
> 
> // Call the function.
> dlog_vprint_(LOG_ID_MAIN, priority, tag, format, args);
> ```

Good solution, I will apply it. Thank you~,
