### ISSUE TITLE
The ESC key should act like the back button of mobile on IoT profile.

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/engine#177]
Default apps behave as if the back button was pressed when the esc key is pressed. 
~and there is no way to terminate the flutter app after launching it(except shell command) on IoT profile :(~

**Comment by swift-kim** [comment]
By the way you can right click on a mouse (if you have) to simulate back key events.

**Comment by swift-kim** [comment]
@bbrto21 Is this feature still needed? Do you have a plan to implement?
