### ISSUE TITLE
Better support for building system-ui apps

### ISSUE THREAD

**Issue by HakkyuKim** [flutter-tizen/engine#208]
I'm still surveying about the subject. This issue is to share and discuss what I'm currently looking into.

*System UI* is an application that runs when a device is powered on. It keeps track and provides control to system-wide setting, status, notification, etc. Examples: lockscreen UI, navigation bar, notification app, status bar, volume UI, ...

I'm posting a youtube link, [What's new in System UI](https://www.youtube.com/watch?v=oLLUDOQxJS8&ab_channel=AndroidDevelopers), so that you can get a sense on what a *system ui* might be in Android.

I'm looking into the following subjects in consideration of some performance metrics such as start-up time, response time, and memory consumption:

- [component based application](https://docs.tizen.org/application/native/guides/applications/component-based-app/)
- [add-to-app](https://docs.google.com/document/d/1fdKRufqUzQvERcqNIUSq-GdabXc4k8VIsClzRElJ6KY/edit)
- [lightweight flutter instances](https://docs.google.com/document/d/1NwiZPWHd1te46eP2GWwIezDV9CdMQkODAMuF5kWdtLw/edit#)

**Comment by bwikbs** [comment]
It's a bit of a silly question..but is there any direction you're thinking about right now?
I mean .. topic is so broad that I have no idea what you're trying to do. Or is it just a step you want to set the direction for?

Anyway, I think challenging topic is cool!!

**Comment by HakkyuKim** [comment]
@bwikbs 
Not a silly question at all! I'm still organizing my thoughts and reading code to see if my plans make sense, but I'll share my thoughts with some details. The plans can change in the future.

The motivation started out from the fact that our internal use of flutter-tizen focuses on building system-ui apps rather than user apps. As opposed to full-screen user apps, system-ui requires flexible and varing window/UI style(e.g. partial screen, top level window, etc) that are common in system-ui scenarios. With that said, the main goal is to support creating a persistent-multi-partial-window app in a single package. Previous works have already contributed to creating these types of apps: multi-app, top level, window resize, partial screen, etc.

Currently I can think of two more tasks(though not small) that needs to be done:

- Support packaging multiple windows app where each window has independent navigation stack.

    My current direction is extending [component based application](https://docs.tizen.org/application/native/guides/applications/component-based-app/) so that each UI component holds a flutter engine similar to Android's [FlutterActivity](https://github.com/flutter-tizen/engine/blob/flutter-2.5.3-tizen/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java) And because start-up/response time and memory consumption are not be negligible, [add-to-app](https://docs.google.com/document/d/1fdKRufqUzQvERcqNIUSq-GdabXc4k8VIsClzRElJ6KY/edit) and [lightweight flutter instances](https://docs.google.com/document/d/1NwiZPWHd1te46eP2GWwIezDV9CdMQkODAMuF5kWdtLw/edit#) are being considered as well.

- Access to WindowManger. (This requires more investigation)

**Comment by bwikbs** [comment]
Thanks for the detailed explanation I wasn't expecting at all! Now I understand!! :+1: 

> My current direction is extending component based application

AFAIK, @bbrto21 is very interested in this. (@bbrto21  Am I right? :smile:  )

> As a side note, I know this doesn't leverage the fact that Flutter is cross-platform, building system-ui with Flutter may not be compelling for platforms with a solid UI framework such as Android, but for Tizen, I hear a lot of complains about coding UI using EFL with the C language.

I think I know what you're talking about :smile: Hopefully this time it will be a meaningful result!!

**Comment by bbrto21** [comment]
@bwikbs 
That's right, actually @HakkyuKim  and I started thinking about this topic together. 
but as you know I haven't made any progress due to other tasks :)

**Comment by swift-kim** [comment]
Just in case you are interested:

Fuchsia once had a system UI based upon Flutter, called Armadillo, in its early days. Unfortunately, it soon had been [replaced](https://9to5google.com/2018/12/26/fuchsia-armadillo-ui-gone) with another graphical shell written in Rust and its source code had completely been removed from the Topaz (Fuchsia's UI layer) repo. As far as I know Armadillo had just been a normal Flutter app which could even be run on the Android platform.

**Comment by HakkyuKim** [comment]
@bbrto21 @bwikbs 
I actually found out about component bases application from @bwikbs, we talk more about it once you finish your current task.

@swift-kim 
Oh I thought Fuchsia still used Flutter in its UI layer, thanks for the info. I hope the decision wasn't solely due to performance reasons, I'll check it out.

**Comment by HakkyuKim** [comment]
To share some progress, I've created a test host runner based on [component based application](https://docs.tizen.org/application/native/guides/applications/component-based-app/): https://github.com/HakkyuKim/flutter-tizen/tree/component-app-embedding.
It requires this engine build: https://github.com/HakkyuKim/engine.

You can't actually run multiple apps(components) at the moment, it requires more work:
- Support `app_control_set_component_id` in app_control plugin(needed to run components from other components or apps).
- Support `Ecore_Wl2_Window`. (The component-based-app framework is built around `Evas_Object`, I'm not sure if it's possible to link with `Ecore_Wl2_Window`.).
- Solving significant delay issue when exiting the app using hardware back key.
- Support new lifecycle events in engine side.

Using the component based host runner will provide the following features:
1. Packaging related UI apps where each requires a separate navigation stack into a single tpk. -> Will save disk space, memory space may be reduced by [lightweight flutter instances](https://docs.google.com/document/d/1NwiZPWHd1te46eP2GWwIezDV9CdMQkODAMuF5kWdtLw/edit#).
2. Support [add to app](https://docs.flutter.dev/development/add-to-app) scenarios(although not a compelling feature for Tizen).

For developing system-ui, I'm focusing on [overlaying views in other apps](https://stackoverflow.com/questions/20461979/how-to-overlay-views-in-other-apps) by accessing something similar to Android's [WindowManager](https://developer.android.com/reference/android/view/WindowManager).
