### ISSUE TITLE
Synchronous keyboard events

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/engine#221]
https://medium.com/flutter/whats-new-in-flutter-2-8-d085b763d181#a407

The keyboard input system is being reworked in the upstream (more processing should be done by the embedder side), so we'll need to make some changes to our embedder sooner or later.

**Comment by xiaowei-guan** [comment]
Related PR:

- https://github.com/flutter/engine/pull/23466
- https://github.com/flutter/engine/pull/23465
- https://github.com/flutter/engine/pull/23467

**Comment by swift-kim** [comment]
@xiaowei-guan Are you working on this or may I take a look?

**Comment by xiaowei-guan** [comment]
> @xiaowei-guan Are you working on this or may I take a look?

I am working on webrtc plugin task, If you want, just do it.
