### ISSUE TITLE
Automatically release CI build artifacts

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/engine#230]
I'd like to automate the release process which is currently being manually done.

https://github.com/flutter-tizen/engine/releases

I'll take a look when I get some time but please feel free to work on this if you're interested. cc @WonyoungChoi

**Comment by WonyoungChoi** [comment]
Opps, I missed this issue. If the engine is rebuilt in the release workflow, probably many parts will be duplicated with the build workflow. Therefore, we need to consider re-organizing workflows for using `Reusable workflow`. https://docs.github.com/en/actions/using-workflows/reusing-workflows.
