### ISSUE TITLE
Need to disable the quick panel pull-down gesture

### ISSUE THREAD

**Issue by nojinjeong** [flutter-tizen/engine#236]
There is a use case where the app needs to disable quickpanel pull-down gesture to prevent users from exiting the app. I know that https://github.com/flutter-tizen/flutter-tizen/issues/246 is fixed by #197. We need a way to control this behavior.

**Comment by swift-kim** [comment]
We will end up with having four `bool` options in

https://github.com/flutter-tizen/engine/blob/c5ee051cc15204b276ad6cac194a11e23e51ab5f/shell/platform/tizen/tizen_renderer.h#L65-L67

if we implement this feature. Maybe we can organize them in some way to make it look cleaner.

**Comment by swift-kim** [comment]
It doesn't seem "right" to control this behavior in the Flutter embedder. Is there any way for the system administrator to globally disable the quick panel or the quick panel gesture (e.g. terminate the quick panel app process)?
