### ISSUE TITLE
[VD] TV내의 App Focus 안보임 이슈

### ISSUE THREAD

**Issue by yman-son** [flutter-tizen/engine#274]
안녕하세요. 

TV에 Sample App을 올려놓고 테스트를 하다보면, 
일부 배경이 흰색을 가진 element에서는 Focus가 잘 눈에 띄지 않아
개선이 가능할지 문의하고자 이슈를 남깁니다. 

혹은 앱 개발자가 Focus를 받은 widget에 대해 테두리를 추가하도록
구현 가이드를 해야할 부분인지 답변 주시면 감사하겠습니다.

http://wiki.vd.sec.samsung.net/pages/viewpage.action?pageId=174034907
자세한 그림은 위의 URL을 참고해 주세요.

**Comment by swift-kim** [comment]
안녕하세요.

앱 코드의 구현상 미숙한 부분으로 보이며 engine/embedder와 무관한 이슈인 것 같습니다. 코드가 없어서 저희가 확인할 방법은 없습니다.

**Comment by yman-son** [comment]
안녕하세요! 질문에 남겼던 URL에 sample code를 첨부했습니다. 
  (https://github.com/VGVentures/slide_puzzle에서 받음. 오래된버전)

여러 테스트 앱을 리모컨을 통한 focus이동시 앱에서의 별도의 처리가 없더라도
focus가된 항목에 대해 약간의 blur처리가 되는 것을 볼 수 있었는데요.

이 부분을 flutter engine에서 처리하는 것으로 생각했고,
이 blur처리를 눈에 명확하게 보이도록 flutter engine에서 변경할지
혹은 앱 개발자가 앱의 UX에 맞게 Focus를 다시 그리도록 유도하는게 맞을지 검토 부탁드립니다.

감사합니다.

**Comment by nojinjeong** [comment]
안녕하세요.

논의 결과 세부적인 부분은 개발자가 앱의 UX에 맞게 설정하는 것이 맞다고 판단됩니다. 

Focus관련해서 https://docs.flutter.dev/development/ui/advanced/focus#focus-widget
참고하셔서 구현하시면 될 것 같습니다.

감사합니다.

**Comment by yman-son** [comment]
답변 감사드립니다
