### ISSUE TITLE
Implement rotation on TizenRendererEvasGL

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/engine#277]
We should fully implement screen rotation on evas gl

![image](https://github.com/bbrto21/temp.github.io/blob/main/images/rotation_evas_gl.gif?raw=true) 

to reproduce this you must use kEvasGL
``` c++
class App : public FlutterApp {
 public:
  bool OnCreate() {
    renderer_type_ = FlutterRendererType::kEvasGL;
    if (FlutterApp::OnCreate()) {
      RegisterPlugins(this);
    }
    return IsRunning();
  }
};
```

**Comment by bbrto21** [comment]
see #71

**Comment by bbrto21** [comment]
I will reopen the issue to actively discuss and resolve this issue.

**Comment by JSUYA** [comment]
@bbrto21 close?
