### ISSUE TITLE
Migrate to the new GpuBufferTexture API

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/engine#285]
https://github.com/flutter/engine/pull/26562#issuecomment-1114156009

The new API was not included in the Flutter 3.0 release but will land in the next stable engine release. We will have to prepare for migration until then.

cc @xiaowei-guan

**Comment by swift-kim** [comment]
The Flutter next version (3.3) will be released soon.

**Comment by xiaowei-guan** [comment]
> xt version (3.3) will be released soo

Ok, I got it.
