### ISSUE TITLE
Enable Evas GL renderer for all profile

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/engine#301]
To provide more options of flutter-tizen's user, I want to open the Evas GL render to all profiles.
I expect that this provides advanced users with the option of selecting a window type for flutter-tizen, or enables using the view of FlutterTizen.

I think the following things are needed.
 - Change from `use_evas_gl_renderer` to `use_evas_gl_renderer_only` in BUILD.gn
    - `use_evas_gl_renderer_only` must be true in the wearable profile only.
 - `FlutterDesktopViewCreateFromNewWindow` must be divided into two APIs.
    - ex) `FlutterDesktopViewCreateFromNewElmWindow` and `FlutterDesktopViewCreateFromNewEcoreWl2Window`
    - therefore, the embedding implementation at flutter-tizen should also be updated.
 - The renderer must be selected according to the view type on runtime.
 - The event loop must be selected according to the renderer type on runtime.

**Comment by bbrto21** [comment]
> ex) FlutterDesktopViewCreateFromNewElmWindow and FlutterDesktopViewCreateFromNewEcoreWl2Window

Alternatively, it would be good to receive the view type as an argument and unify it into one API.
```c++
FlutterDesktopViewRef FlutterDesktopViewCreateFrom(FlutterDektopViewType type /*,may be additional args*/ );
```

**Comment by JSUYA** [comment]
> > ex) FlutterDesktopViewCreateFromNewElmWindow and FlutterDesktopViewCreateFromNewEcoreWl2Window
> 
> Alternatively, it would be good to receive the view type as an argument and unify it into one API.
> 
> ```c++
> FlutterDesktopViewRef FlutterDesktopViewCreateFrom(FlutterDektopViewType type /*,may be additional args*/ );
> ```

I have a question. Which window should FlutterApp choose in a situation where it is a profile other than wearable (both evasgl and ecorewl2 windows are supported)?
Do we also leave this up to the user?

**Comment by bbrto21** [comment]
I recommend using `ecorewl2` as before.  from a refactoring point of view, I think it would be better to keep the behavior of a FlutterApp&Service while handle this issue. 
To achieve this, I think the tool should provide a define to represent a profile when building the app.
@swift-kim Is profile macro already provided while building an app?

**Comment by swift-kim** [comment]
@bbrto21 Currently you can specify a device profile but not a renderer type.

```sh
flutter-tizen build tpk -p wearable  # The wearable embedder implicitly uses the Evas GL renderer.
flutter-tizen build tpk -p common    # The IoT embedder implicitly uses the Ecore Wl2 renderer.
```
