### ISSUE TITLE
Remove app lifecycle-related APIs

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/engine#327]
The C# platform channel API (`BasicMessageChannel` and `StringCodec`) has now been implemented, so we may consider removing the following APIs from the embedder and reimplement them in the embedding side.

- FlutterDesktopEngineNotifyAppIsInactive
- FlutterDesktopEngineNotifyAppIsResumed
- FlutterDesktopEngineNotifyAppIsPaused
- FlutterDesktopEngineNotifyAppIsDetached

More "channel" (internal plugin) implementations might be moved to the embedding side but there are some limitations or the cost outweighs the benefit.

- `AccessibilityChannel`: Maybe.
- `AppControlChannel`: Implementing and maintaining the C# version of the code is too expensive.
- `NavigationChannel`, `PlatformChannel`, `SettingsChannel`: Depend on `rapidjson` and `JsonMethodCodec`.
- `KeyEventChannel`, `PlatformViewChannel`, `TextInputChannel`, `WindowChannel`: Tightly coupled with the embedder's view implementation.

**Comment by swift-kim** [comment]
Maybe we can use Tizen's built-in [JSON-GLib](https://docs.tizen.org/application/native/api/wearable/4.0/group__OPENSRC__JSONGLIB__FRAMEWORK.html) as a replacement of rapidjson for the implementation of `NavigationChannel` and etc.

**Comment by bbrto21** [comment]
> The C# platform channel API (`BasicMessageChannel` and `StringCodec`) has now been implemented, so we may consider removing the following APIs from the embedder and reimplement them in the embedding side.

What are the benefits of implementing lifecycle channels for both C# and C++?

**Comment by swift-kim** [comment]
The main purpose is to keep the embedder API set simple (we can remove the four redundant functions). I don't think this activity is very necessary at the moment. I just wanted to share this idea as an issue for those who might have a similar idea.
