### ISSUE TITLE
Improve text input on NUI view

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/engine#340]
The current text composition is not properly supported on only NUI view.
Text composition should be properly supported like others.

![image](https://github.com/bbrto21/temp.github.io/blob/main/images/keyboard_on_NUI.gif?raw=true)

**Comment by JSUYA** [comment]
Fixed https://github.com/flutter-tizen/engine/pull/349
Fixed https://github.com/flutter-tizen/flutter-tizen/pull/448
