### ISSUE TITLE
Provide a way to release focus from the view

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/engine#341]
Flutter-tizen now supports views not only single page app. 
However, when mixed the view with Native UI components, once the view is focused, the focus cannot be released again via key input.
This is an important issue for profiles where touch screens are not available.

![image](https://github.com/bbrto21/temp.github.io/blob/main/images/focus.gif?raw=true)

**Comment by swift-kim** [comment]
Do you know how other platforms handle the case? Does the value of `handled` (in `FlutterTizenView::OnKey`) differ when a focus has or has not been moved by Flutter?

**Comment by bbrto21** [comment]
> Do you know how other platforms handle the case? 

I don't know yet :disappointed: 

>Does the value of handled (in FlutterTizenView::OnKey) differ when a focus has or has not been moved by Flutter?

The value of `handled` is not different both case. :confused:

**Comment by Swanseo0** [comment]
It seems to have found a reason for this issue.

This is because of `EVAS_EVENT_FLAG_ON_HOLD`.

There is a part that adds `EVAS_EVENT_FLAG_ON_HOLD` to `key_event->event_flags` in the addition of `EVAS_CALLBACK_KEY_DOWN` of `tizen_view_element.cc`.
By adding `EVAS_EVENT_FLAG_ON_HOLD`, Focus moving inside the view could work normally, but the operation of the callback that releases focus of the view seems to be blocked.

**Comment by JSUYA** [comment]
> This is because of EVAS_EVENT_FLAG_ON_HOLD.

I will check

**Comment by JSUYA** [comment]
> By adding EVAS_EVENT_FLAG_ON_HOLD, Focus moving inside the view could work normally, but the operation of the callback that releases focus of the view seems to be blocked.

EVAS_EVENT_FLAG_ON_HOLD is absolutely necessary for downkey and upkey events for flutterview's key consumption.
We may need to asynchronously dispatch unhandled events in flutterview in conjunction with https://github.com/flutter-tizen/engine/issues/331.

**Comment by bbrto21** [comment]
> It seems to have found a reason for this issue.
> 
> This is because of `EVAS_EVENT_FLAG_ON_HOLD`.
> 
> There is a part that adds `EVAS_EVENT_FLAG_ON_HOLD` to `key_event->event_flags` in the addition of `EVAS_CALLBACK_KEY_DOWN` of `tizen_view_element.cc`. By adding `EVAS_EVENT_FLAG_ON_HOLD`, Focus moving inside the view could work normally, but the operation of the callback that releases focus of the view seems to be blocked.

@Swanseo0 
I think I can make a simple blur(removes keyboard focus from view) method using this fact. 
I'll make a PR.

**Comment by bbrto21** [comment]
[Here](https://github.com/bbrto21/engine/commit/77dd4dbdf03ee96c2a3577661dd0f21a4e324fc8) is my attempt. 
We can make that remove keyboard focus from view, instead of exiting the app or doing nothing, when there is no place to go back in the navigation stack.

![image](https://github.com/bbrto21/temp.github.io/blob/main/images/blur.gif?raw=true)

**Comment by Swanseo0** [comment]
> How do you feel about this? 

If we need to enter a back key to get out of `view`, how about adding the process of entering `view`?
When there are multiple `views`, considering the scenarios that select, enter, perform, and get out, I think it will be easier for the user to have a process of entering `view`.

What do you think about this? @bbrto21

**Comment by JSUYA** [comment]
@Swanseo0 @bbrto21 @swift-kim 
I think that's a good.
It would be better for the user for focus move if the hightlight box displayed with the flutterview before entering. I think this can be supported by embedding.
[select (focus with hightlight box) - enter - get out(focus with hightlight box)]

**Comment by bbrto21** [comment]
@Swanseo0
That's a good point of view. If you don't mind, why don't you suggest a new issue?
