### ISSUE TITLE
Flutter 2.0.1 migration issues

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/engine#49]
- Clang 12 build flag (`-Wno-psabi`) issue
  - Fuschia/Linux build now uses clang 12 by default but the Tizen toolchain is still based on clang 10.
  - Building the Tizen engine with the Fuschia toolchain has failed because required libraries are not available for `armv7-linux-gnueabi` target (see `buildtools/linux-x64/clang/lib`).
  - Thus, similarly to the `-Wno-non-c-typedef-for-linkage` flag, we have to remove the new flag from `build/config/compiler/BUILD.gn` manually.
- `TextInputModel` API changes (https://github.com/flutter/engine/pull/21612, https://github.com/flutter/engine/pull/21854)
  - Done!
- SDK artifacts cross-compilation issue
  - The same build error as https://github.com/flutter/flutter/issues/74322 which was caused by https://github.com/flutter/engine/pull/20254.
  - We don't need to cross-build SDK artifacts for Tizen armv7l and x86. So we need to patch the build rule temporarily. (I'm not going to PR it in the upstream right now.)
- `flutter_texture_registrar.h` API conflicts
  - The following APIs have been added (https://github.com/flutter/engine/pull/19405):
    - `FlutterDesktopRegistrarGetTextureRegistrar`
    - `FlutterDesktopTextureRegistrarRegisterExternalTexture`
    - `FlutterDesktopTextureRegistrarUnregisterExternalTexture`
    - `FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable`
  - but we already have:
    - `FlutterPluginRegistrarGetTexture`
    - `FlutterRegisterExternalTexture`
    - `FlutterUnregisterExternalTexture`
    - `FlutterMarkExternalTextureFrameAvailable`
  - I tried to remove our header and use theirs by renaming the functions in `flutter_tizen.cc` file, but the parameter `tbm_surface` was not available for `FlutterDesktopTextureRegistrarMarkExternalTextureFrameAvailable`. How should we deal with this? @xiaowei-guan @bbrto21 
  - My attempt: https://github.com/swift-kim/engine/commit/1d72ddb14901ee9b50f0fb36e4aaf7671a9c6232 (see the commented out section in `flutter_tizen.cc`)
- Embedder API changes?
  - ~I haven't checked yet.~ Done

**Comment by xuelian-bai** [comment]
for the texture part, linux didn't handle GLES extension OES_EGL_image_external, which is an extension of GLES. so things are different.

**Comment by swift-kim** [comment]
I don't quite understand what you mean. I told nothing about linux in the above comment. You may build the current flutter-2.0.1-tizen branch yourself and understand what the current problem is.

**Comment by xuelian-bai** [comment]
sorry, it's windows, not linux. I mean windows/linux like desktop use GL instead of GLES. 
I think, windows texture is applied in scenario like webrtc, the texture data is from CPU, but in our case, the data we use is from GPU, we can't do CPU-GPU copy, so a handle is tranferred instead of a buffer in ExternalTextureGL::CopyPixelBuffer

**Comment by xiaowei-guan** [comment]
For the texture part. 
The common part  is get data from pixel buffer(CPU->GPU)
Our implementation is get data from tbm surface(GPU->GPU)
so we need provider two sets of interface:
1.we need modify tbm interface name to make it more clearly.
2.we should implement pixel buffer part.

**Comment by swift-kim** [comment]
2.0.1 has landed. Actually a new hotfix (2.0.2) was released in the upstream but will not update to it since there's no or little difference.
