### ISSUE TITLE
Investigate why SkSL shaders cannot be collected on Tizen devices

### ISSUE THREAD

**Issue by xiaowei-guan** [flutter-tizen/engine#55]

**Comment by bwikbs** [comment]
Can you explain in more detail what the problem is?

**Comment by swift-kim** [comment]
https://flutter.dev/docs/perf/rendering/shader

If you run an app which has animations with the following command, a json file containing shader information should be generated in the project directory. On Tizen, the shaders are simply not captured and thus the file is not generated. I haven't looked into this issue in much detail. Note that there won't be a lot of performance gain we can obtain with this optimization so this is not a critical issue.

```
flutter-tizen run --profile --cache-sksl
```

**Comment by bwikbs** [comment]
@swift-kim thanks :smile:

**Comment by swift-kim** [comment]
You may analyze performance benefits from caching the shaders on Android devices first, and then decide whether this issue is worth investigating or not for Tizen.

**Comment by xiaowei-guan** [comment]
### What is shader compilation jank?
If an app has janky animations during the first run, and later becomes smooth for the same animation, then it’s very likely due to shader compilation jank.
### What is SKSL warmup?
The SkSL shaders can be packaged into the app, and get warmed up (pre-compiled) when an end-user first opens the app, thereby reducing the compilation jank in later animations.
![shader-jank-df154d7366290e80e57ad785f5e860fccfe0177c1ff0474f9f9eabf4609bcaa2](https://user-images.githubusercontent.com/60122246/114173880-6d0bb900-996a-11eb-9ee1-04c824501308.gif)

**Comment by xiaowei-guan** [comment]
If we want to generate flutter.sksl.json，we need set persistent_cache_path when call FlutterEngineRun.

**Comment by swift-kim** [comment]
@xiaowei-guan Great. Can you see any performance diff on Tizen devices when you launch an app (e.g. gallery) multiple times after setting the path?

**Comment by xiaowei-guan** [comment]
> @xiaowei-guan Great. Can you see any performance diff on Tizen devices when you launch an app (e.g. gallery) multiple times after setting the path?
Although could get SKSL shaders file, But there are some minor issues, I am trying to fix it.

**Comment by xiaowei-guan** [comment]
> @xiaowei-guan Great. Can you see any performance diff on Tizen devices when you launch an app (e.g. gallery) multiple times after setting the path?

Do we support command:
flutter-tizen build tpk --bundle-sksl-path flutter_03.sksl.json

**Comment by swift-kim** [comment]
As far as I remember the file is included within flutter_assets directory which is not platform-specific, so yes.

**Comment by xiaowei-guan** [comment]
How to get SKSL shaders file.
1.set persistent_cache_path when call FlutterEngineRun .
2.flutter run --profile --cache-sksl
How to build tpk with SKSL shaders file
flutter-tizen build tpk --bundle-sksl-path flutter_03.sksl.json

**Comment by xiaowei-guan** [comment]
I launch a Flutter app with animation, no obvious effect. 
And I build gallery failed, I will launch gallery app with SKSL later.

**Comment by swift-kim** [comment]
I couldn't see any obvious effect either and the cached shaders even delayed the execution.

```
Application                              STIME     PSS     RSS
io.flutter.demo.gallery                   1232  117894  133341
io.flutter.demo.gallery_sksl              2555  128066  143513
```

Measured on rpi4 (arm64) with the gallery app (native app, hw-acceleration on).
