### ISSUE TITLE
typo in function name: FlutterDestoryWindow

### ISSUE THREAD

**Issue by wiertel** [flutter-tizen/engine#56]
https://github.com/flutter-tizen/engine/blob/e629333c726cb9492e14f73aadc616e9ab0a666f/shell/platform/tizen/public/flutter_tizen.h#L63

The "Destory" occurs 27 times in the repo. This one is part of public API and should probably be fixed. But I guess current name should continue to work to maintain compatibility.

**Comment by swift-kim** [comment]
What a mistake. The change in `flutter_tizen.h` will not break anything as long as we simultaneously update https://github.com/flutter-tizen/flutter-tizen/blob/master/nuget/Tizen.Flutter.Embedding/Interop.cs as well. The change will definitely affect apps already created with the C++ language option (`flutter-tizen create --tizen-language cpp`, https://github.com/flutter-tizen/flutter-tizen/blob/master/templates/app/cpp/src/flutterapp.cc) but the native app type support is still experimental so it doesn't matter much.
