### ISSUE TITLE
Consider tmb format when using external texture

### ISSUE THREAD

**Issue by bbrto21** [flutter-tizen/engine#70]
external texture's format are fixed as GL_RGBA8, However, the TBM surface has a variety of formats. 
We've started to worry about this while developing our plugin. 
here is our discussion https://github.com/flutter-tizen/plugins/pull/70#discussion_r617066957

**Comment by bbrto21** [comment]
By the way, when I tried to create an issue by referencing a conversation from the plugin repository, I couldn't select the engine repository. Does anyone know why?

**Comment by bwikbs** [comment]
Don't you know what you can't do... What do you want to do? Engine issue reference?

**Comment by bbrto21** [comment]
I mean this
![Screenshot from 2021-04-22 09-01-38](https://user-images.githubusercontent.com/1579532/115637747-e1bbfb80-a34b-11eb-8707-bf4b531ba550.png)

**Comment by xuelian-bai** [comment]
tbm surface has lots of formats, but not everyone is supported by hardware. for eglimage, normally, YUV/NV12 formats could be supported by most Tizen devices, if you need, we can try to support them. RGBA is just a common format which could be supported by everyone.

**Comment by xuelian-bai** [comment]
tbm surface has lots of formats, but not everyone is supported by hardware. For eglimage, when tbm surface is transffered into eglimage, GPU driver will read the tbm buffer and check the formats, not NV12/YUV420 formats are supported on most Tizen devices, these formats will be converted inside GPU. But the mentioned GL_RGBA8 format is not for tbm surface, it's texture format, they are different.

**Comment by bwikbs** [comment]
Ummm... Then who converts the tbm format to the format used by texture?  driver?

**Comment by xuelian-bai** [comment]
yes, inside eglCreateImageKHR(), GPU driver will check tbm format, and conversion will be done inside GPU if necessary, and you can also use shader to do the conversion if GPU driver don't support it.

**Comment by bwikbs** [comment]
@xuelian-bai Thanks! :smiley:
