### ISSUE TITLE
"xkbcommon: ERROR: couldn't find a Compose file for locale" on app launch

### ISSUE THREAD

**Issue by pwasowski2** [flutter-tizen/engine#91]
This issue has been reported in https://github.com/flutter-tizen/engine/issues/53:

> Non-fatal error "xkbcommon: ERROR: couldn't find a Compose file for locale" on app launch (unrelated to Flutter)

Reproduction by @bbrto21:
> 
>     Launch Settings
>     Go - Language and input
>     Go - Display language
>     Choose a language other than English
>     Launch flutter-app

`dlog` output:

> E/ConsoleMessage(24758): xkbcommon: ERROR: couldn't find a Compose file for locale "pl_PL.UTF-8"

**Comment by pwasowski2** [comment]
Continuing the conversation from #53:

@swift-kim, @bbrto21, I have run a .NET app on my TM1 and got the error in the dlog:

> I/DOTNET_LAUNCHER(13337): xkbcommon: ERROR: couldn't find a Compose file for locale "pl_PL.UTF-8"

The log does not appear when I run native or web apps, so it seems to be a problem with .NET runtime.
I guess, we should just report it to the .NET runtime team - what do you think about it?

**Comment by swift-kim** [comment]
I'm part of the .NET runtime team. I'll ask one of my colleagues first. 😉

**Comment by swift-kim** [comment]
I submitted an error report: https://github.sec.samsung.net/dotnet/home/issues/403 (intenal GitHub)

**Comment by swift-kim** [comment]
We may filter out this error message by simply adding a filter in the log reader. 😎

(Adding a new if statement between line 626-629: https://github.com/flutter-tizen/flutter-tizen/blob/f0ad603ef30f811b99510e07a6eeed25f950459b/lib/tizen_device.dart#L627)

**Comment by bbrto21** [comment]
It seems that this is no longer an issue we need to handle. how about closing this issue?

**Comment by swift-kim** [comment]
https://github.com/flutter-tizen/flutter-tizen/pull/131 work arounds this issue.

**Comment by pwasowski2** [comment]
We have received the following message about this behavior, from C# runtime team:

> Actually if there is no 'pl.PL.UTF-8' found in system, it should be displayed as it can be important information in some cases. Please note that "pl _ PL.UTF-8" is not the locale available on any system.
> 
>     E/ConsoleMessage(24758): xkbcommon: ERROR: couldn't find a Compose file for locale "pl_PL.UTF-8"
> 
> Anyway, the error message you mentioned is sometimes perceived as an error by some developer(s)/tester(s).
> Thus, I removed the error message from libxkbcommon package only if the locale has not been set to 'en_US.UTF-8'.
> FYI, we only use 'en_US.UTF-8' as a primary locale for key mapping for UI app(s) in Tizen.

A patch for this problem has already been merged to `xkbcommon`.

> We may filter out this error message by simply adding a filter in the log reader. 😎
> 
> (Adding a new if statement between line 626-629: https://github.com/flutter-tizen/flutter-tizen/blob/f0ad603ef30f811b99510e07a6eeed25f950459b/lib/tizen_device.dart#L627)

@swift-kim, it seems, that the problem has been fixed in `xkbcommon`, so I close this issue as @bbrto21 suggests ;)
