### ISSUE TITLE
Investigate the advantage of enabling SkSL warmup

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/engine#99]
### What is shader compilation jank?

https://flutter.dev/docs/perf/rendering/shader

### How to enable SkSL warm-up on Tizen?

1. Set the `FlutterProjectArgs.persistent_cache_path` value to either a system temp directory or the app cache directory before starting the engine. Alternatively, the cache directory can be set by implementing `fml::paths::GetCachesDirectory()` in `fml/platform/linux/paths_linux.cc` (not tested). Shaders will be stored to this directory on the first run of an app, and the cached shaders will be used on subsequent runs.

2. You can optionally bundle the shaders with a tpk (as a json file in `res/flutter_assets`) to accelerate the first run of the app on other devices: https://flutter.dev/docs/perf/rendering/shader#how-to-use-sksl-warmup

### Pros and cons

- Reduced shader compilation janks (not confirmed on Tizen - how can we measure this accurately?)
- Increased app startup latency because cached/bundled shaders need to be precompiled
  - The last measurement result: https://github.com/flutter-tizen/engine/issues/55#issuecomment-831005612
- Slightly larger app size due to bundled shaders

### Read more

- https://medium.com/flutter/whats-new-in-flutter-2-2-fd00c65e2039#7ed0

**Comment by xuelian-bai** [comment]
as the result I shown, sksl warmup can reduce time in GrGLProgramBuilder::finalize(), then reduce DrawSnapshot time about 200ms, but this will result in more time before OnMakecurrent in the same thread, that's why you can't see any improvement, I will check why.

**Comment by swift-kim** [comment]
@xuelian-bai Thank you for sharing. I was just to correct what you mentioned about the "launch time" because the sksl warmup typically doesn't reduce the startup time but rather increases it. From the medium link that I provided in the above comment, you will see

> To avoid jank, Flutter has provided the ability to cache shaders during a training run, which are then packaged and bundled with an app, and compiled before the first frame while the Flutter Engine is starting up.

> App startup latency is longer because the bundled shaders need to be precompiled.

**Comment by swift-kim** [comment]
Currently the following message is logged out to the console when an app is run with the `--verbose-system-logs` option in debug mode.

```
E/ConsoleMessage( 4279): [WARNING:flutter/common/graphics/persistent_cache.cc(258)] Could not acquire the persistent cache directory. Caching of GPU resources on disk is disabled.
E/ConsoleMessage( 4279): [INFO:persistent_cache.cc(227)] No sksl asset found.
E/ConsoleMessage( 4279): [INFO:gpu_surface_gl.cc(79)] Found 0 SkSL shaders; precompiled 0
```

**Comment by xuelian-bai** [comment]
did you set the path FlutterProjectArgs.persistent_cache_path?

**Comment by swift-kim** [comment]
@xuelian-bai No. I know why the error is displayed. The above comment just states the current status.

**Comment by swift-kim** [comment]
This will not be necessary if https://github.com/flutter-tizen/engine/issues/326 is implemented. Let's focus on https://github.com/flutter-tizen/engine/issues/326.
